### ISSUE TITLE
Logs for previous pods

### ISSUE THREAD

**Issue by piotr-00** [kubetail-org/kubetail#99] opened 2024-07-02 09:07 UTC
It would be nice to see logs for previous (inactive) pods.
e.g.
1. Cron jobs run and complete, when completed logs are not accessible via kubetail.
2. When pod crashes, the reason why it crashed can't be checked via kubetail.

thanks

**Comment by amorey** [comment] 2024-07-02 21:02
Thanks for the suggestion! I'll take a look. As long as the log files are still on disk in the cluster we should be able to expose them in the kubetail UI.

**Comment by amorey** [comment] 2024-07-17 03:36
@piotr-00 This issue should be fixed in the latest version (0.6.3). To upgrade using helm you can run this command:
```console
helm repo update kubetail
helm upgrade kubetail kubetail/kubetail --namespace kubetail
```

Let me know if that fixes the problem!

**Closed** 2024-07-17 18:13 UTC
Labels: enhancement

**Comment by dihmandrake** [comment] 2024-07-18 13:06
Just checked this on stopped, successful CronJob and can happily report that it works.
Thanks very much for implementing this feature

**Comment by amorey** [comment] 2024-07-18 17:23
Great! Happy to hear it's working. Let me know if you run into any other issues or have more suggestions.

**Comment by piotr-00** [comment] 2024-07-19 17:51
Great news!
Is it possible to see that on deployments and replicasets also?

When I kill pod from stateful replicaset and have opened console for that pod, I can see logs from previous and new pod, however when I refresh the page - logs from new pod remains only.

For deployment it's pretty much the same  as previously. I'm not sure if is it possible to see logs from all previous pods created by deployment - it that case each pod has different name and schema is not updating automatically. There is an option in Kubetail to select specific deployment but it shows pods which are actually active. If I kill a pod from deployment, I need to refresh console view to see new pod, and old one disappears. 

Thanks

**Comment by amorey** [comment] 2024-07-19 18:08
> Is it possible to see that on deployments and replicasets also?

Currently, this isn't possible because kubernetes deletes pods automatically after they are replaced in deployments, replicaSets, statefulsets, and daemonsets and once pods are deleted, the associated log files are deleted too. In order for to view logs for deleted pods we'll need to add a persistence layer to Kubetail (stay tuned).

> When I kill pod from stateful replicaset and have opened console for that pod, I can see logs from previous and new pod, however when I refresh the page - logs from new pod remains only.

Unfortunately this is expected behavior because once a pod is deleted, the only copy of the log records is what's in your browser cache and that copy disappears on page reload. I was thinking about adding a warning when you navigate away from the page but in the long run the only protection against losing those log records is to add a persistence layer.
